// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Viewer interface {
	IsViewer()
}

type AuctionConnection struct {
	PageInfo *PageInfo               `json:"pageInfo"`
	Edges    []AuctionConnectionEdge `json:"edges"`
}

type AuctionConnectionEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Auction `json:"node"`
}

type AuctionFilter struct {
	Ids      []string `json:"ids"`
	Rooms    []string `json:"rooms"`
	Products []string `json:"products"`
}

type AuctionResult struct {
	Auction *Auction `json:"auction"`
}

type BidStepTableConnection struct {
	PageInfo *PageInfo                    `json:"pageInfo"`
	Edges    []BidStepTableConnectionEdge `json:"edges"`
}

type BidStepTableConnectionEdge struct {
	Cursor string        `json:"cursor"`
	Node   *BidStepTable `json:"node"`
}

type BidStepTableFilter struct {
	Ids        []string `json:"ids"`
	Name       *string  `json:"name"`
	Organizers []string `json:"organizers"`
}

type BidStepTableResult struct {
	BidStepTable *BidStepTable `json:"bidStepTable"`
}

type ConsumerConnection struct {
	PageInfo *PageInfo                `json:"pageInfo"`
	Edges    []ConsumerConnectionEdge `json:"edges"`
}

type ConsumerConnectionEdge struct {
	Cursor string    `json:"cursor"`
	Node   *Consumer `json:"node"`
}

type ConsumerFilter struct {
	Ids      []string          `json:"ids"`
	Nickname *string           `json:"nickname"`
	Form     map[string]string `json:"form"`
}

type ConsumerResult struct {
	Consumer *Consumer `json:"consumer"`
}

type OfferConnection struct {
	PageInfo *PageInfo             `json:"pageInfo"`
	Edges    []OfferConnectionEdge `json:"edges"`
}

type OfferConnectionEdge struct {
	Cursor string `json:"cursor"`
	Node   *Offer `json:"node"`
}

type OfferFilter struct {
	Ids       []string `json:"ids"`
	Consumers []string `json:"consumers"`
	Auctions  []string `json:"auctions"`
}

type OfferResult struct {
	Offer *Offer `json:"offer"`
}

type OrganizerConnection struct {
	PageInfo *PageInfo                 `json:"pageInfo"`
	Edges    []OrganizerConnectionEdge `json:"edges"`
}

type OrganizerConnectionEdge struct {
	Cursor string     `json:"cursor"`
	Node   *Organizer `json:"node"`
}

type OrganizerFilter struct {
	Ids  []string `json:"ids"`
	Name *string  `json:"name"`
}

type OrganizerResult struct {
	Orgainzer *Organizer `json:"orgainzer"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor"`
	EndCursor       *string `json:"endCursor"`
}

type ProductConnection struct {
	PageInfo *PageInfo               `json:"pageInfo"`
	Edges    []ProductConnectionEdge `json:"edges"`
}

type ProductConnectionEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Product `json:"node"`
}

type ProductFilter struct {
	Ids        []string `json:"ids"`
	Name       *string  `json:"name"`
	Organizers []string `json:"organizers"`
}

type ProductResult struct {
	Product *Product `json:"product"`
}

type RoomConnection struct {
	PageInfo *PageInfo            `json:"pageInfo"`
	Edges    []RoomConnectionEdge `json:"edges"`
}

type RoomConnectionEdge struct {
	Cursor string `json:"cursor"`
	Node   *Room  `json:"node"`
}

type RoomFilter struct {
	Ids        []string `json:"ids"`
	Name       *string  `json:"name"`
	Address    *string  `json:"address"`
	Orgainzers []string `json:"orgainzers"`
	Consumers  []string `json:"consumers"`
}

type RoomResult struct {
	Room *Room `json:"room"`
}

type UpdateProductInput struct {
	ProductID string `json:"productId"`
	Name      string `json:"name"`
}
