// This file was generated by codegen/graphql_resolvers. DO NOT EDIT.
package resolvers

import (
	"context"
	"iu7-2022-sd-labs/buisness/ports/repositories"
	"iu7-2022-sd-labs/server/models"
)

func (r *Resolver) generatedPagination__Auctions(ctx context.Context, first *int, after *string, filter *models.AuctionFilter) (*models.AuctionConnection, error) {
	ents, err := r.auctionInteractor.Find(&repositories.AuctionFindParams{
		Filter: filter.Into(&repositories.AuctionFilter{}),
		Order: &repositories.AuctionOrder{
			By:   repositories.AuctionOrderFieldCreationDate,
			Desc: true,
		},
		Slice: models.FillForwardSlice(first, after, &repositories.ForwardSlice{}),
	})
	if err != nil {
		return nil, Wrap(err, "auction interactor find")
	}

	if len(ents) == 0 {
		return &models.AuctionConnection{PageInfo: &models.PageInfo{}}, nil
	}

	objs := models.AuctionEdgesArrayFromEntites(ents)

	hasNextPage := false
	if first != nil {
		hasNextPage = len(objs) > *first
		objs = objs[:len(objs)-1]
	}

	return &models.AuctionConnection{
		PageInfo: &models.PageInfo{
			HasNextPage: hasNextPage,
			StartCursor: &objs[0].Cursor,
			EndCursor:   &objs[len(objs)-1].Cursor,
		},
		Edges: objs,
	}, nil
}
