// This file was generated by codegen/graphql_resolvers. DO NOT EDIT.
package resolvers

import (
	"context"
	"iu7-2022-sd-labs/buisness/ports/repositories"
	"iu7-2022-sd-labs/server/models"
)

func (r *Resolver) generatedPagination__BidStepTables(ctx context.Context, first *int, after *string, filter *models.BidStepTableFilter) (*models.BidStepTableConnection, error) {
	ents, err := r.bidStepTableInteractor.Find(&repositories.BidStepTableFindParams{
		Filter: filter.Into(&repositories.BidStepTableFilter{}),
		Order: &repositories.BidStepTableOrder{
			By:   repositories.BidStepTableOrderFieldCreationDate,
			Desc: true,
		},
		Slice: models.FillForwardSlice(first, after, &repositories.ForwardSlice{}),
	})
	if err != nil {
		return nil, Wrap(err, "bidStepTable interactor find")
	}

	if len(ents) == 0 {
		return &models.BidStepTableConnection{PageInfo: &models.PageInfo{}}, nil
	}

	objs := models.BidStepTableEdgesArrayFromEntites(ents)

	hasNextPage := false
	if first != nil {
		hasNextPage = len(objs) > *first
		objs = objs[:len(objs)-1]
	}

	return &models.BidStepTableConnection{
		PageInfo: &models.PageInfo{
			HasNextPage: hasNextPage,
			StartCursor: &objs[0].Cursor,
			EndCursor:   &objs[len(objs)-1].Cursor,
		},
		Edges: objs,
	}, nil
}
