// This file was generated by codegen/graphql_resolvers. DO NOT EDIT.
package resolvers

import (
	"context"
	"iu7-2022-sd-labs/buisness/ports/repositories"
	"iu7-2022-sd-labs/server/models"
)

func (r *Resolver) generatedPagination__Consumers(ctx context.Context, first *int, after *string, filter *models.ConsumerFilter) (*models.ConsumerConnection, error) {
	ents, err := r.consumerInteractor.Find(&repositories.ConsumerFindParams{
		Filter: filter.Into(&repositories.ConsumerFilter{}),
		Order: &repositories.ConsumerOrder{
			By:   repositories.ConsumerOrderFieldCreationDate,
			Desc: true,
		},
		Slice: models.FillForwardSlice(first, after, &repositories.ForwardSlice{}),
	})
	if err != nil {
		return nil, Wrap(err, "consumer interactor find")
	}

	if len(ents) == 0 {
		return &models.ConsumerConnection{PageInfo: &models.PageInfo{}}, nil
	}

	objs := models.ConsumerEdgesArrayFromEntites(ents)

	hasNextPage := false
	if first != nil {
		hasNextPage = len(objs) > *first
		objs = objs[:len(objs)-1]
	}

	return &models.ConsumerConnection{
		PageInfo: &models.PageInfo{
			HasNextPage: hasNextPage,
			StartCursor: &objs[0].Cursor,
			EndCursor:   &objs[len(objs)-1].Cursor,
		},
		Edges: objs,
	}, nil
}
