// This file was generated by codegen/graphql_resolvers. DO NOT EDIT.
package resolvers

import (
	"context"
	"iu7-2022-sd-labs/buisness/ports/repositories"
	"iu7-2022-sd-labs/server/models"
)

func (r *Resolver) generatedPagination__Offers(ctx context.Context, first *int, after *string, filter *models.OfferFilter) (*models.OfferConnection, error) {
	ents, err := r.offerInteractor.Find(&repositories.OfferFindParams{
		Filter: filter.Into(&repositories.OfferFilter{}),
		Order: &repositories.OfferOrder{
			By:   repositories.OfferOrderFieldCreationDate,
			Desc: true,
		},
		Slice: models.FillForwardSlice(first, after, &repositories.ForwardSlice{}),
	})
	if err != nil {
		return nil, Wrap(err, "offer interactor find")
	}

	if len(ents) == 0 {
		return &models.OfferConnection{PageInfo: &models.PageInfo{}}, nil
	}

	objs := models.OfferEdgesArrayFromEntites(ents)

	hasNextPage := false
	if first != nil {
		hasNextPage = len(objs) > *first
		objs = objs[:len(objs)-1]
	}

	return &models.OfferConnection{
		PageInfo: &models.PageInfo{
			HasNextPage: hasNextPage,
			StartCursor: &objs[0].Cursor,
			EndCursor:   &objs[len(objs)-1].Cursor,
		},
		Edges: objs,
	}, nil
}
