// This file was generated by codegen/graphql_resolvers. DO NOT EDIT.
package resolvers

import (
	"context"
	"iu7-2022-sd-labs/buisness/ports/repositories"
	"iu7-2022-sd-labs/server/models"
)

func (r *Resolver) generatedPagination__Products(ctx context.Context, first *int, after *string, filter *models.ProductFilter) (*models.ProductConnection, error) {
	ents, err := r.productInteractor.Find(&repositories.ProductFindParams{
		Filter: filter.Into(&repositories.ProductFilter{}),
		Order: &repositories.ProductOrder{
			By:   repositories.ProductOrderFieldCreationDate,
			Desc: true,
		},
		Slice: models.FillForwardSlice(first, after, &repositories.ForwardSlice{}),
	})
	if err != nil {
		return nil, Wrap(err, "product interactor find")
	}

	if len(ents) == 0 {
		return &models.ProductConnection{PageInfo: &models.PageInfo{}}, nil
	}

	objs := models.ProductEdgesArrayFromEntites(ents)

	hasNextPage := false
	if first != nil {
		hasNextPage = len(objs) > *first
		objs = objs[:len(objs)-1]
	}

	return &models.ProductConnection{
		PageInfo: &models.PageInfo{
			HasNextPage: hasNextPage,
			StartCursor: &objs[0].Cursor,
			EndCursor:   &objs[len(objs)-1].Cursor,
		},
		Edges: objs,
	}, nil
}
