// This file was generated by codegen/graphql_resolvers. DO NOT EDIT.
package resolvers

import (
	"context"
	"iu7-2022-sd-labs/buisness/ports/repositories"
	"iu7-2022-sd-labs/server/models"
)

func (r *Resolver) generatedPagination__Rooms(ctx context.Context, first *int, after *string, filter *models.RoomFilter) (*models.RoomConnection, error) {
	ents, err := r.roomInteractor.Find(&repositories.RoomFindParams{
		Filter: filter.Into(&repositories.RoomFilter{}),
		Order: &repositories.RoomOrder{
			By:   repositories.RoomOrderFieldCreationDate,
			Desc: true,
		},
		Slice: models.FillForwardSlice(first, after, &repositories.ForwardSlice{}),
	})
	if err != nil {
		return nil, Wrap(err, "room interactor find")
	}

	if len(ents) == 0 {
		return &models.RoomConnection{PageInfo: &models.PageInfo{}}, nil
	}

	objs := models.RoomEdgesArrayFromEntites(ents)

	hasNextPage := false
	if first != nil {
		hasNextPage = len(objs) > *first
		objs = objs[:len(objs)-1]
	}

	return &models.RoomConnection{
		PageInfo: &models.PageInfo{
			HasNextPage: hasNextPage,
			StartCursor: &objs[0].Cursor,
			EndCursor:   &objs[len(objs)-1].Cursor,
		},
		Edges: objs,
	}, nil
}
