// This file was generated by codegen/gorm_repository. DO NOT EDIT.
package gorm_repositories

import (
	"iu7-2022-sd-labs/buisness/ports/repositories"

	"fmt"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"iu7-2022-sd-labs/buisness/entities"
)

type AuctionRepository struct{ db *gorm.DB }

func (r *GORMRepository) Auction() repositories.AuctionRepository {
	return &AuctionRepository{r.db}
}

func (r *AuctionRepository) Get(id string) (entities.Auction, error) {
	obj := Auction{}
	ent := entities.NewAuction()

	if err := r.db.Take(&obj, "id = ?", id).Error; err != nil {
		return ent, Wrap(err, "db take")
	}

	obj.Into(&ent)
	return ent, nil
}

func (r *AuctionRepository) Lock(id string) (entities.Auction, error) {
	obj := Auction{}
	ent := entities.NewAuction()

	err := r.db.Clauses(clause.Locking{
		Strength: "UPDATE",
		Table:    clause.Table{Name: clause.CurrentTable},
	}).
		Take(&obj, "id = ?", id).
		Error
	if err != nil {
		return ent, Wrap(err, "db select for update")
	}

	obj.Into(&ent)
	return ent, nil
}

func (r *AuctionRepository) orderQuery(query *gorm.DB, order *repositories.AuctionOrder) (*gorm.DB, error) {
	if order == nil {
		return query, nil
	}

	column, exists := auctionFieldToColumn[order.By]
	if !exists {
		return nil, fmt.Errorf("column for field \"%s\" is unknown", order.By)
	}

	query = query.Order(clause.OrderByColumn{
		Column: clause.Column{Name: column},
		Desc:   order.Desc,
	})

	return query, nil
}

func (r *AuctionRepository) sliceQuery(query *gorm.DB, order *repositories.AuctionOrder, slice *repositories.ForwardSlice) (*gorm.DB, error) {
	if slice == nil {
		return query, nil
	}

	column, exists := auctionFieldToColumn[order.By]
	if !exists {
		return nil, fmt.Errorf("column for field \"%s\" is unknown", order.By)
	}

	var err error
	query, err = sliceQuery(query, column, order.Desc, slice)
	return query, Wrap(err, "sliceQuery")
}

func (r *AuctionRepository) Find(params *repositories.AuctionFindParams) ([]entities.Auction, error) {
	query := r.db.Model(&Auction{})

	if params != nil {
		var err error
		if query, err = r.filterQuery(query, params.Filter); err != nil {
			return nil, Wrap(err, "filter query")
		}

		if query, err = r.orderQuery(query, params.Order); err != nil {
			return nil, Wrap(err, "order query")
		}

		if query, err = r.sliceQuery(query, params.Order, params.Slice); err != nil {
			return nil, Wrap(err, "slice query")
		}
	}

	var objs []Auction
	if err := query.Find(&objs).Error; err != nil {
		return nil, Wrap(err, "db find")
	}

	ents := make([]entities.Auction, 0, len(objs))

	for _, obj := range objs {
		ent := entities.NewAuction()
		obj.Into(&ent)
		ents = append(ents, ent)
	}

	return ents, nil
}

func (r *AuctionRepository) Create(ent *entities.Auction) error {
	obj := Auction{}
	obj.From(ent)

	if err := r.db.Create(&obj).Error; err != nil {
		return Wrap(err, "db create")
	}

	obj.Into(ent)
	return nil
}

func (r *AuctionRepository) Delete(id string) (entities.Auction, error) {
	obj := Auction{}
	ent := entities.NewAuction()

	err := r.db.Transaction(func(tx *gorm.DB) error {
		err := r.db.Clauses(clause.Locking{
			Strength: "UPDATE",
			Table:    clause.Table{Name: clause.CurrentTable},
		}).
			Take(&obj, "id = ?", id).
			Error

		if err != nil {
			return Wrap(err, "db select for update")
		}

		if err := r.db.Delete(&obj).Error; err != nil {
			return Wrap(err, "db delete")
		}

		return nil
	})

	if err != nil {
		return ent, Wrap(err, "db transaction")
	}

	obj.Into(&ent)
	return ent, nil
}
