// This file was generated by codegen/gorm_repository. DO NOT EDIT.
package gorm_repositories

import (
	"iu7-2022-sd-labs/buisness/ports/repositories"

	"fmt"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

type BlockListRepository struct{ db *gorm.DB }

func (r *GORMRepository) BlockList() repositories.BlockListRepository {
	return &BlockListRepository{r.db}
}

func (r *BlockListRepository) orderQuery(query *gorm.DB, order *repositories.BlockListOrder) (*gorm.DB, error) {
	if order == nil {
		return query, nil
	}

	column, exists := blockListFieldToColumn[order.By]
	if !exists {
		return nil, fmt.Errorf("column for field \"%s\" is unknown", order.By)
	}

	query = query.Order(clause.OrderByColumn{
		Column: clause.Column{Name: column},
		Desc:   order.Desc,
	})

	return query, nil
}
