// This file was generated by codegen/gorm_repository. DO NOT EDIT.
package gorm_repositories

import (
	"iu7-2022-sd-labs/buisness/ports/repositories"

	"fmt"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"iu7-2022-sd-labs/buisness/entities"
)

type OfferRepository struct{ db *gorm.DB }

func (r *GORMRepository) Offer() repositories.OfferRepository {
	return &OfferRepository{r.db}
}

func (r *OfferRepository) Get(id string) (entities.Offer, error) {
	obj := Offer{}
	ent := entities.NewOffer()

	if err := r.db.Take(&obj, "id = ?", id).Error; err != nil {
		return ent, Wrap(err, "db take")
	}

	obj.Into(&ent)
	return ent, nil
}

func (r *OfferRepository) orderQuery(query *gorm.DB, order *repositories.OfferOrder) (*gorm.DB, error) {
	if order == nil {
		return query, nil
	}

	column, exists := offerFieldToColumn[order.By]
	if !exists {
		return nil, fmt.Errorf("column for field \"%s\" is unknown", order.By)
	}

	query = query.Order(clause.OrderByColumn{
		Column: clause.Column{Name: column},
		Desc:   order.Desc,
	})

	return query, nil
}

func (r *OfferRepository) sliceQuery(query *gorm.DB, order *repositories.OfferOrder, slice *repositories.ForwardSlice) (*gorm.DB, error) {
	if slice == nil {
		return query, nil
	}

	column, exists := offerFieldToColumn[order.By]
	if !exists {
		return nil, fmt.Errorf("column for field \"%s\" is unknown", order.By)
	}

	var err error
	query, err = sliceQuery(query, column, order.Desc, slice)
	return query, Wrap(err, "sliceQuery")
}

func (r *OfferRepository) Find(params *repositories.OfferFindParams) ([]entities.Offer, error) {
	query := r.db.Model(&Offer{})

	if params != nil {
		var err error
		if query, err = r.filterQuery(query, params.Filter); err != nil {
			return nil, Wrap(err, "filter query")
		}

		if query, err = r.orderQuery(query, params.Order); err != nil {
			return nil, Wrap(err, "order query")
		}

		if query, err = r.sliceQuery(query, params.Order, params.Slice); err != nil {
			return nil, Wrap(err, "slice query")
		}
	}

	var objs []Offer
	if err := query.Find(&objs).Error; err != nil {
		return nil, Wrap(err, "db find")
	}

	ents := make([]entities.Offer, 0, len(objs))

	for _, obj := range objs {
		ent := entities.NewOffer()
		obj.Into(&ent)
		ents = append(ents, ent)
	}

	return ents, nil
}

func (r *OfferRepository) Create(ent *entities.Offer) error {
	obj := Offer{}
	obj.From(ent)

	if err := r.db.Create(&obj).Error; err != nil {
		return Wrap(err, "db create")
	}

	obj.Into(ent)
	return nil
}
