// Code generated by mockery v2.12.0. DO NOT EDIT.

package mocks

import (
	entities "iu7-2022-sd-labs/buisness/entities"

	mock "github.com/stretchr/testify/mock"

	repositories "iu7-2022-sd-labs/buisness/ports/repositories"

	testing "testing"
)

// AuctionRepository is an autogenerated mock type for the AuctionRepository type
type AuctionRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: auction
func (_m *AuctionRepository) Create(auction *entities.Auction) error {
	ret := _m.Called(auction)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Auction) error); ok {
		r0 = rf(auction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *AuctionRepository) Delete(id string) (entities.Auction, error) {
	ret := _m.Called(id)

	var r0 entities.Auction
	if rf, ok := ret.Get(0).(func(string) entities.Auction); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entities.Auction)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Find provides a mock function with given fields: params
func (_m *AuctionRepository) Find(params *repositories.AuctionFindParams) ([]entities.Auction, error) {
	ret := _m.Called(params)

	var r0 []entities.Auction
	if rf, ok := ret.Get(0).(func(*repositories.AuctionFindParams) []entities.Auction); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Auction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*repositories.AuctionFindParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: id
func (_m *AuctionRepository) Get(id string) (entities.Auction, error) {
	ret := _m.Called(id)

	var r0 entities.Auction
	if rf, ok := ret.Get(0).(func(string) entities.Auction); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entities.Auction)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Lock provides a mock function with given fields: id
func (_m *AuctionRepository) Lock(id string) (entities.Auction, error) {
	ret := _m.Called(id)

	var r0 entities.Auction
	if rf, ok := ret.Get(0).(func(string) entities.Auction); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entities.Auction)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuctionRepository creates a new instance of AuctionRepository. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuctionRepository(t testing.TB) *AuctionRepository {
	mock := &AuctionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
