// Code generated by mockery v2.12.0. DO NOT EDIT.

package mocks

import (
	entities "iu7-2022-sd-labs/buisness/entities"

	mock "github.com/stretchr/testify/mock"

	repositories "iu7-2022-sd-labs/buisness/ports/repositories"

	testing "testing"
)

// BidStepTableRepository is an autogenerated mock type for the BidStepTableRepository type
type BidStepTableRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: organizer
func (_m *BidStepTableRepository) Create(organizer *entities.BidStepTable) error {
	ret := _m.Called(organizer)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.BidStepTable) error); ok {
		r0 = rf(organizer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: params
func (_m *BidStepTableRepository) Find(params *repositories.BidStepTableFindParams) ([]entities.BidStepTable, error) {
	ret := _m.Called(params)

	var r0 []entities.BidStepTable
	if rf, ok := ret.Get(0).(func(*repositories.BidStepTableFindParams) []entities.BidStepTable); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.BidStepTable)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*repositories.BidStepTableFindParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: id
func (_m *BidStepTableRepository) Get(id string) (entities.BidStepTable, error) {
	ret := _m.Called(id)

	var r0 entities.BidStepTable
	if rf, ok := ret.Get(0).(func(string) entities.BidStepTable); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entities.BidStepTable)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: organizer
func (_m *BidStepTableRepository) Update(organizer *entities.BidStepTable) error {
	ret := _m.Called(organizer)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.BidStepTable) error); ok {
		r0 = rf(organizer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBidStepTableRepository creates a new instance of BidStepTableRepository. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewBidStepTableRepository(t testing.TB) *BidStepTableRepository {
	mock := &BidStepTableRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
