// Code generated by mockery v2.12.0. DO NOT EDIT.

package mocks

import (
	entities "iu7-2022-sd-labs/buisness/entities"

	mock "github.com/stretchr/testify/mock"

	repositories "iu7-2022-sd-labs/buisness/ports/repositories"

	testing "testing"
)

// ConsumerRepository is an autogenerated mock type for the ConsumerRepository type
type ConsumerRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: organizer
func (_m *ConsumerRepository) Create(organizer *entities.Consumer) error {
	ret := _m.Called(organizer)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Consumer) error); ok {
		r0 = rf(organizer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: params
func (_m *ConsumerRepository) Find(params *repositories.ConsumerFindParams) ([]entities.Consumer, error) {
	ret := _m.Called(params)

	var r0 []entities.Consumer
	if rf, ok := ret.Get(0).(func(*repositories.ConsumerFindParams) []entities.Consumer); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Consumer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*repositories.ConsumerFindParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: id
func (_m *ConsumerRepository) Get(id string) (entities.Consumer, error) {
	ret := _m.Called(id)

	var r0 entities.Consumer
	if rf, ok := ret.Get(0).(func(string) entities.Consumer); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entities.Consumer)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: organizer
func (_m *ConsumerRepository) Update(organizer *entities.Consumer) error {
	ret := _m.Called(organizer)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Consumer) error); ok {
		r0 = rf(organizer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewConsumerRepository creates a new instance of ConsumerRepository. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewConsumerRepository(t testing.TB) *ConsumerRepository {
	mock := &ConsumerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
