// Code generated by mockery v2.12.0. DO NOT EDIT.

package mocks

import (
	entities "iu7-2022-sd-labs/buisness/entities"

	mock "github.com/stretchr/testify/mock"

	repositories "iu7-2022-sd-labs/buisness/ports/repositories"

	testing "testing"
)

// OfferRepository is an autogenerated mock type for the OfferRepository type
type OfferRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: auction
func (_m *OfferRepository) Create(auction *entities.Offer) error {
	ret := _m.Called(auction)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Offer) error); ok {
		r0 = rf(auction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: params
func (_m *OfferRepository) Find(params *repositories.OfferFindParams) ([]entities.Offer, error) {
	ret := _m.Called(params)

	var r0 []entities.Offer
	if rf, ok := ret.Get(0).(func(*repositories.OfferFindParams) []entities.Offer); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Offer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*repositories.OfferFindParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: id
func (_m *OfferRepository) Get(id string) (entities.Offer, error) {
	ret := _m.Called(id)

	var r0 entities.Offer
	if rf, ok := ret.Get(0).(func(string) entities.Offer); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entities.Offer)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOfferRepository creates a new instance of OfferRepository. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewOfferRepository(t testing.TB) *OfferRepository {
	mock := &OfferRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
