// Code generated by mockery v2.12.0. DO NOT EDIT.

package mocks

import (
	entities "iu7-2022-sd-labs/buisness/entities"

	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// OfferPayService is an autogenerated mock type for the OfferPayService type
type OfferPayService struct {
	mock.Mock
}

// PayLink provides a mock function with given fields: offer
func (_m *OfferPayService) PayLink(offer *entities.Offer) (string, error) {
	ret := _m.Called(offer)

	var r0 string
	if rf, ok := ret.Get(0).(func(*entities.Offer) string); ok {
		r0 = rf(offer)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*entities.Offer) error); ok {
		r1 = rf(offer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOfferPayService creates a new instance of OfferPayService. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewOfferPayService(t testing.TB) *OfferPayService {
	mock := &OfferPayService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
